### ISSUE TITLE
当方法返回值包含error类型时，执行报错

### ISSUE THREAD

**Issue by anden007** [dengsgo/go-decorator#6]
`func (m *Demo) Run(a string, b string) (result string, err error) {
	result = fmt.Sprintf("%s %s", a, b)
	return
}`
报错：
`panic: interface conversion: interface is nil, not error

goroutine 1 [running]:
go-decorator-demo/demo.(*Demo).Run(0x9395a0, {0x84af04, 0x5}, {0x84af09, 0x5})
        D:/GoProjects/go-decorator-demo/demo/demo.go:11 +0x27e
main.main()
        D:/GoProjects/go-decorator-demo/main.go:10 +0x3c
exit status 2`

貌似在interface{}转换为error类型时发生错误，stackoverflow中有[解决方案](https://stackoverflow.com/questions/57781058/how-to-cast-nil-interface-to-nil-other-interface)

**Comment by dengsgo** [comment]
感谢反馈！该问题已在 `v0.21.0` 修复，可以使用下面的命令升级：

```shell
$ go install github.com/dengsgo/go-decorator/cmd/decorator@latest
```
